### ISSUE TITLE
missing dependencies in Ubuntu 20.04 instructions.

### ISSUE THREAD

**Issue by jwstolk** [magiblot/turbo#15]
Following the "Detailed build instructions for Ubuntu 20.04" in readme.md, running on Ubuntu (server) 20.04.2 LTS,

I'm missing the dependency: pkg-config (easy to resolve).

But then I'm also missing the libxcb dependency, as per error:

    -- Checking for module 'xcb'
    --   No package 'xcb' found
    CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
      A required package was not found
    Call Stack (most recent call first):
      /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
      deps/libclipboard/CMakeLists.txt:66 (pkg_check_modules)

and "apt-cache search libxcb" shows a lot of packages, and I'm not sure which one (or all?) is actually needed.

EDIT: On further inspection, xcb is a (replacement for) X11 library, which may be an issue on my non-GUI Ubuntu Server installation.

I was only installing to test out libtvision, and how it would work over SHH or (in Windows PuTTY). I now moved testing to a GUI version of Ubuntu. As long as libtvision doesn't depend on X11 I'm happy. Unless it is particularly easy to solve the dependency, the simplest solution would be to rename the instructions to  "Detailed build instructions for Ubuntu 20.04 (Desktop)"

I'm very impressed with how well it works over SSH/PuTTY, also the window/screen resizing!

**Comment by magiblot** [comment]
Hi, jwstolk!

Yes, the build instructions became obsolete after I added clipboard support and I haven't updated them yet. Sorry for the inconvenience.

The package you need is `libxcb1-dev`, I think.

> EDIT: On further inspection, xcb is a (replacement for) X11 library, which may be an issue on my non-GUI Ubuntu Server installation.
> 
> I was only installing to test out libtvision, and how it would work over SHH or (in Windows PuTTY). I now moved testing to a GUI version of Ubuntu. As long as libtvision doesn't depend on X11 I'm happy. Unless it is particularly easy to solve the dependency, the simplest solution would be to rename the instructions to "Detailed build instructions for Ubuntu 20.04 (Desktop)"

You don't have to worry about this. libxcb is used to integrate the in-app clipboard with the graphical session clipboard. Nothing bad happens if there's no graphical session.

You can take advantage of this if your local environment is a X11 session. The `-X` argument of `ssh` enables X11 forwarding, which will allow Turbo to access your clipboard even if running in a remote server.

> I'm very impressed with how well it works over SSH/PuTTY, also the window/screen resizing!

Thanks for the recognition. The fact that in 2021 people still get impressed by Turbo Vision says a lot about the average usability of Unix TUI applications.

Cheers.

**Comment by jwstolk** [comment]
Thanks! libxcb1-dev worked great.

It downloaded just 730kb. xorg-sgml-doctools and 6 other dev packages, not all of X11.
