### ISSUE TITLE
COLUMNS and LINES env

### ISSUE THREAD

**Issue by pmp-p** [magiblot/turbo#17]
Please add support to follow those so Turbo does not expand to full terminal space when it is not wanted

( sidenote: can help to solve https://github.com/magiblot/turbo/issues/12 in a very simple way as demonstrated with another editor here https://pix.mathieui.net/o/kZTPc.png, even more powerfull when using VT420 with configurables margins for drawing children with their own scrolling zones )

**Comment by magiblot** [comment]
Hi Paul.

What exactly are you trying to accomplish? If Turbo only draws itself on a small region of the terminal, how will the empty area be useful to you? What is sidenode?

Cheers.

**Comment by pmp-p** [comment]
oops thanks, "sidenode" was a typo i meant "sidenote".

I'm about to make a TurboP(ython) kind of program, the empty space left on terminal is all useable for VT100/420 and sixel graphics of running program  it's just a matter of setting the margins before running/switching tasks. and no terminal multiplexer are not an option for my design.

But really it's not about to accomplish something special but more about following established standards that application and ncurses already follow (see man resize at environment section).

**Comment by magiblot** [comment]
Ah, thanks for the clarification.

It took me some time to understand what was going on, because `tilde` in my machine does not react to `COLUMNS` or `LINES` in any special way. After trying several applications, I found `vi` exhibiting the behaviour described by the man pages.

This is `tvdemo` with `COLUMNS=80`:

![Screenshot_20210414_204840](https://user-images.githubusercontent.com/20713561/114766473-babb6380-9d66-11eb-880c-ba8a890876f6.png)

Commit 8cc5097cb28f14982562298a077ce7baccac6faf brings the change to this application.

Cheers.

**Comment by pmp-p** [comment]
works very well thanks !
