### ISSUE TITLE
Mac book air big sur cpu usage 100%

### ISSUE THREAD

**Issue by vampiebar** [magiblot/turbo#20]
in mac os big sur cpu usage ( when only open one cc file ) 100% cpu..
What can it be the reason?

**Comment by magiblot** [comment]
I'm not sure because I have never tested on macOS, but from what I can gather the problem is probably in the `poll` system call, which does not play nicely with `/dev/tty`.

The Turbo Vision library has a setting to avoid reading from `/dev/tty` and use standard input/output instead. Does the problem persist if you run Turbo with the environment variable `TVISION_USE_STDIO` set to `1`? (in the command-line shell: `TVISION_USE_STDIO=1 turbo` or `export TVISION_USE_STDIO=1; turbo`)

**Comment by vampiebar** [comment]
TVISION_USE_STDIO=1 turbo 
or export TVISION_USE_STDIO=1; turbo

yes CPU is ok now everything is optimized.. what is missing when I do use stdio ?
any side effect?

**Comment by okbob** [comment]
st 16. 6. 2021 v 14:57 odesílatel magiblot ***@***.***>
napsal:

> I'm not sure because I have never tested on macOS, but from what I can
> gather the problem is probably in the poll system call, which does not
> play nicely with /dev/tty.
>
> The Turbo Vision library has a setting to avoid reading from /dev/tty and
> use standard input/output instead. Does the problem persist if you run
> Turbo with the environment variable TVISION_USE_STDIO set to 1? (in the
> command-line shell: TVISION_USE_STDIO=1 turbo or export
> TVISION_USE_STDIO=1; turbo)
>

yes, /dev/tty and poll doesn't work together on macOS.

I use (in pspg)

#ifndef __APPLE__

<--><-->/* macOS can't use poll() on /dev/tty */
<--><-->state.tty = fopen("/dev/tty", "r+");

#endif

<--><-->if (!state.tty)
<--><--><-->state.tty = fopen(ttyname(fileno(stdout)), "r");

<--><-->if (!state.tty)
<--><-->{
<--><--><-->if (!isatty(fileno(stderr)))
<--><--><--><-->leave("missing a access to terminal device");

<--><--><-->state.tty = stderr;
<--><-->}

**Comment by magiblot** [comment]
> what is missing when I do use stdio ? any side effect?

No, in the case of Turbo there's nothing you need to worry about.

> I use (in pspg)

Thanks for chiming in. Actually, I first learned about this problem when I spotted this commit in pspg: https://github.com/okbob/pspg/commit/776c8e89a062925e222bd8cc91ae238d96fb6b54
