### ISSUE TITLE
Capitalize First

### ISSUE THREAD

**Issue by amay5267** [magiblot/turbo#31]
[aabb.zip](https://github.com/magiblot/turbo/files/8943436/aabb.zip)
Hi guys
I miss capitalize words function in this text editor.
I want tranform text like aa bb cc into Aa Bb Cc
I suggest ctrl + 3 keyboard shortcut in Settings.

Take a look at this demo:
aabb.cc

**Comment by magiblot** [comment]
Okay. I have looked into this and it is not hard to implement. But it won't be possible to use that key shortcut, since `Ctrl+Number` is not detected by regular Unix terminal emulators. Other key shortcuts will likely have the same issue, so instead I'll just create a menu entry for this action, which you'll be able to access with a few key presses (as in `Alt+F+U = File > Suspend`).

**Comment by amay5267** [comment]
Perfect! 
Probably off topic but i have 2 more functions in the works that i will implement myself called All Caps(uppercase) and All Low(lowercase).

**Comment by magiblot** [comment]
> Probably off topic but i have 2 more functions in the works that i will implement myself called All Caps(uppercase) and All Low(lowercase).

Don't worry about that! I was going to add them anyway, since these three functions usually go together. And the Unicode case conversion functions are already implemented in Scintilla.
